name: Map Keboola Branches
description: Discovers new remote Keboola Connection branches and maps them to newly created git branches
outputs:
  kbc_branch_id:
    description: 'Branch ID'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.kbc-set-branch-id.outputs.kbc_branch_id }}
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: pip install github_action_utils PyGithub
      shell: bash
    - name: Pass Inputs to Shell
      run: |
        echo "KBC_STORAGE_API_TOKEN=${{ inputs.kbcSapiToken }}" >> $GITHUB_ENV
      shell: bash
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Get Keboola Branch ID or create new one
      id: kbc-set-branch-id
      run: python .github/actions/kbc_cli_map_branches/src/map_branches.py
      shell: bash