name: Pull (Branch)
on:
  workflow_dispatch:
    inputs:
      kbcBranchId:
        description: 'Destination Branch ID (OPT)'
        default: ''
      createBranchIfNotExists:
        description: 'Create new Keboola Dev Branch if not mapped (OPT)'
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
permissions:
  contents: write
env:
  KBC_STORAGE_API_TOKEN: ${{ secrets.KBC_STORAGE_API_TOKEN }}
jobs:
  kbc_pull:
    # Automatic pull can be canceled by push
    concurrency:
     group: main_branch
     cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Keboola as Code CLI
        uses: ./.github/actions/install
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      # GET BRANCH ID
      - uses: actions/checkout@v4
      - name: Get Keboola Branch ID
        id: get_branch_id
        uses: ./.github/actions/kbc_set_branch_id
        with:
          kbcSapiToken: ${{ secrets.KBC_STORAGE_API_TOKEN }}
          createBranchIfNotExists: ${{ github.event.inputs.createBranchIfNotExists }}
          kbcBranchId: ${{ github.event.inputs.kbcBranchId }}
      # Pull remote project's state
      - name: Pull from Keboola Connection
        id: kbc_pull_step
        run: |
          set -eo pipefail
          export KBC_BRANCH_ID=${{ steps.get_branch_id.outputs.kbcBranchId }}
          kbc pull --force 2>&1 | tee "$RUNNER_TEMP/log.txt"
      # Automatic pull can be canceled by push, wait a while
      - name: Wait
        run: sleep 20
      # Commit message contains date and output of the pull command
      - name: Commit and push
        run: |
          currentDate=`date +%Y-%m-%d:%T%Z`
          pull_log=`cat "$RUNNER_TEMP/log.txt"`
          git config --global user.name 'Keboola CLI'
          git config --global user.email 'keboola-cli@users.noreply.github.com'
          git add -A
          git commit -a -m "Automatic pull $currentDate" -m "$pull_log" || true
          git push
