name: TEST ACTION
on:
  workflow_dispatch:
    inputs:
      kbcBranchId:
        description: 'Destination Branch ID (OPT)'
        default: ''
      createBranchIfNotExists:
        description: 'Create new Dev Branch if none is mapped and branch with the same name does not exist'
        default: 'false'
permissions:
  contents: write

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test get branch id
    steps:
      - uses: actions/checkout@v4
      - name: Test
        id: get_branch_id
        uses: ./.github/actions/kbc_set_branch_id
        with:
          kbcSapiToken: ${{ secrets.KBC_STORAGE_API_TOKEN }}
          createBranchIfNotExists: ${{ github.event.inputs.createBranchIfNotExists }}
          kbcBranchId: ${{ github.event.inputs.kbcBranchId }}
      - name: Print branch id
        run: echo ${{ steps.get_branch_id.outputs.kbc_branch_id }}