name: TEST ACTION
on:
  workflow_dispatch:
    inputs:
      kbcBranchId:
        description: 'Destination Branch ID (OPT)'
        default: ''
      createBranchIfNotExists:
        description: 'Create new Dev Branch if none is mapped and branch with the same name does not exist'
        default: 'false'
permissions:
  contents: write

jobs:
  test-create-branch:
    runs-on: ubuntu-latest
    name: Test get branch id
    steps:
      - uses: actions/checkout@v4
      - name: Map
        id: map_cli_branches
        uses: ./.github/actions/kbc_cli_map_branches
        env:
          GITHUB_TOKEN: ${{ github.token }}